### ISSUE TITLE
Dangerous for controller users: Game loses focus

### ISSUE THREAD

**Issue by ununseptium** [lekeno/edr#122]
Title says it all i just flew into a star because the game lost it's focus as the EDR Status message appeared.

**Comment by lekeno** [comment]
Hi, thanks for filing an issue.
It's unfortunately not easy to fix (an issue with the overlay itself which is a separate piece of code: https://github.com/inorton/EDMCOverlay

In previous versions of EDR, the warmup message would tell you to "Check that ED has the focus".
I've re-added that warning via the server side messages feature.

Maybe, this could be avoided by having the warmup message occur on the main menu, since a user would have to give ED the focus in order to interact with the menu?

**Comment by lekeno** [comment]
Made the warning a client side thing instead of server side.
