### ISSUE TITLE
Have EDR clients use mirrored Inara info on EDR server

### ISSUE THREAD

**Issue by lekeno** [lekeno/edr#174]
It's probably more efficient to have the EDR backend do the Inara API calls and provide a global cache than having each EDR clients do the Inara calls and rely on a per client cache.

**Comment by Athanasius** [comment]
Not to mention that you're putting 'your' Inara API key out there in the config.ini contained in the release .zip.  That's really not the intended use of such API keys.  I do wonder about the security implications of that Firebase API key in there as well (but for all I know that one is purely read-only).

I'd highly recommend you change things so that you ask the EDR User for their own Inara API key to use for that functionality.

**Comment by lekeno** [comment]
@Athanasius the Firebase API Key is [meant to be public](https://stackoverflow.com/questions/37482366/is-it-safe-to-expose-firebase-apikey-to-the-public)
