### ISSUE TITLE
No automatic update

### ISSUE THREAD

**Issue by Sparfell-git** [lekeno/edr#276]
Hi

Fir some reason, the automatic update from 1.00 to 1.01, when closing and opening again EDMC, did not work, I had to add the files manually.

**Comment by lekeno** [comment]
Sorry to hear this... 

Was this the first time that the auto-update failed?
Were you already in-game when you noticed the pending update?
How long did you wait?

**Comment by Sparfell-git** [comment]
1) yep, was the first time
2) don't really remember, but I remember trying several times to exit edmc and launch it again ( while the game was not running ), but the message for the update stayed there
3) I did not really try to wait as previously it was rather fast

**Comment by lekeno** [comment]
Thanks.
I'm wondering if this might be because of an antivirus deciding to block either the download, or holding a lock on a file that needs to be updated / overwritten.

If it happens again, could you keep a copy of EDMarketConnector.log from your temp folder?
This file gets overwritten when EDMC is launched. It might contain some additional hints.

**Comment by Sparfell-git** [comment]
For the record, I switched on my old computer, and EDR updated normally. I have the same MS antivirus/firewall in both cases. We'll see what happens at the next update ;).

**Comment by Sparfell-git** [comment]
Same problem with the automatic update from 1.01 to 1.02 not working. But I have noticed that I seem to have a ( read/write authorisation ) problem with a root directory. So the problem does not seem to be related to EDR per se.
