### ISSUE TITLE
py-3.7 branch should work.

### ISSUE THREAD

**Issue by frog2001** [lekeno/edr#322]
py-3.7 branch should work.

_Originally posted by @lekeno in https://github.com/lekeno/edr/issues/270#issuecomment-650487422_

**Comment by frog2001** [comment]
Hello!
I tried to get EDR working with the EDMC V 3.99.1.0.
Unfortunatly i cannot get it to work.
You mentioned at firecrack to copy the pyton files of 1.0.8 into the existing Plugin folder. I Tried this, and had no go.
Then i saw your py-3.7 brach and wanted to give it a go. I meda a clean 1.0.7 plugin folder and copied the pyton files of this branch in. Also with negative resoults.
So i belive there is a an error somewhere, prevnting the plugin to start, since there is no Edr folder in the settings tab of EDMC. Edr is the name of the Folder iunder plugins. All worked fine, till the 3.4.6 release which was still in pyton 2.x.
sSo i wantede you to give a heads up.
Hope to see you soon in Game
Frog2001

**Comment by lekeno** [comment]
I think that's because the repository lacks the updated EDMCOverlay files.

So, try with the just released 1.0.8 (official), let the auto-update take care of it or reinstall from the [EDR v1.0.8 zip attached to the release](https://github.com/lekeno/edr/releases/latest). 

It should work (crossing fingers).
