### ISSUE TITLE
Add search for specific Odyssey settlements

### ISSUE THREAD

**Issue by Habilya** [lekeno/edr#469]
Hello, please add a search for odyssey settlements

by specific parameters
type : mining settlement (can be a parameter)
rule form : Anarchy (can be hardcoded)
security level : 3 (Can be hardcoded)

and those within 500 L.y.  from the querying CMDR.

explanation, 
anarchy settlement = no heat (fines)
security level = quantity and quality of loot in the settlement.

Please do that and you will be dayily praised and worshiped by Odyssey on foot players.

**Comment by lekeno** [comment]
That would be useful indeed.
I'm not sure how feasible this is but I will look into it.

**Comment by lekeno** [comment]
It should be possible to find settlements controlled by an anarchy, and of a specific economy. However, there isn't much data about the security level. I've landed some code in a branch but it's probably not fully functional yet. I'll see how well this work in practice. 

I might have to change from "always return the nearest matching settlement" to "return the next nearest settlement" or a parameter to "find the n-th nearest settlement" so that one could cycle through different settlements in a system to hopefully find one of the desired security level.

**Comment by lekeno** [comment]
Beyond the Odyssey anarchy settlement types below, is there any interest in other type of settlement (government and/or eco)?
 - Anarchy
 - Anarchy Agriculture
 - Anarchy Extraction
 - Anarchy High Tech
 - Anarchy Industrial
 - Anarchy Military
 - Anarchy Tourism

**Comment by lekeno** [comment]
Done in V2.7.0
